/// 130+ languages — mirrors the original app's youtube_asr_languages scope.
/// [code] = translation target code, [fa] = Persian label, [native] = endonym.
class Lang {
  final String code;
  final String fa;
  final String native;
  final String flag;
  const Lang(this.code, this.fa, this.native, this.flag);
}

const List<Lang> kLanguages = [
  Lang('af', 'آفریکانس', 'Afrikaans', '🇿🇦'),
  Lang('sq', 'آلبانیایی', 'Shqip', '🇦🇱'),
  Lang('am', 'امهری', 'አማርኛ', '🇪🇹'),
  Lang('ar', 'عربی', 'العربية', '🇸🇦'),
  Lang('hy', 'ارمنی', 'Հայերեն', '🇦🇲'),
  Lang('as', 'آسامی', 'অসমীয়া', '🇮🇳'),
  Lang('ay', 'آیمارا', 'Aymar', '🇧🇴'),
  Lang('az', 'آذربایجانی', 'Azərbaycan', '🇦🇿'),
  Lang('bm', 'بامبارا', 'Bamanankan', '🇲🇱'),
  Lang('eu', 'باسک', 'Euskara', '🇪🇸'),
  Lang('be', 'بلاروسی', 'Беларуская', '🇧🇾'),
  Lang('bn', 'بنگالی', 'বাংলা', '🇧🇩'),
  Lang('bho', 'بوجپوری', 'भोजपुरी', '🇮🇳'),
  Lang('bs', 'بوسنیایی', 'Bosanski', '🇧🇦'),
  Lang('bg', 'بلغاری', 'Български', '🇧🇬'),
  Lang('ca', 'کاتالان', 'Català', '🇪🇸'),
  Lang('ceb', 'سبویی', 'Cebuano', '🇵🇭'),
  Lang('zh-CN', 'چینی ساده‌شده', '简体中文', '🇨🇳'),
  Lang('zh-TW', 'چینی سنتی', '繁體中文', '🇹🇼'),
  Lang('co', 'کُرسی', 'Corsu', '🇫🇷'),
  Lang('hr', 'کرواتی', 'Hrvatski', '🇭🇷'),
  Lang('cs', 'چکی', 'Čeština', '🇨🇿'),
  Lang('da', 'دانمارکی', 'Dansk', '🇩🇰'),
  Lang('dv', 'دیوهی', 'ދިވެހި', '🇲🇻'),
  Lang('doi', 'دوگری', 'डोगरी', '🇮🇳'),
  Lang('nl', 'هلندی', 'Nederlands', '🇳🇱'),
  Lang('en', 'انگلیسی', 'English', '🇬🇧'),
  Lang('eo', 'اسپرانتو', 'Esperanto', '🌍'),
  Lang('et', 'استونیایی', 'Eesti', '🇪🇪'),
  Lang('ee', 'اوه', 'Eʋegbe', '🇬🇭'),
  Lang('fil', 'فیلیپینی', 'Filipino', '🇵🇭'),
  Lang('fi', 'فنلاندی', 'Suomi', '🇫🇮'),
  Lang('fr', 'فرانسوی', 'Français', '🇫🇷'),
  Lang('fy', 'فریسی', 'Frysk', '🇳🇱'),
  Lang('gl', 'گالیسی', 'Galego', '🇪🇸'),
  Lang('ka', 'گرجی', 'ქართული', '🇬🇪'),
  Lang('de', 'آلمانی', 'Deutsch', '🇩🇪'),
  Lang('el', 'یونانی', 'Ελληνικά', '🇬🇷'),
  Lang('gn', 'گوارانی', 'Avañe’ẽ', '🇵🇾'),
  Lang('gu', 'گجراتی', 'ગુજરાતી', '🇮🇳'),
  Lang('ht', 'هائیتی', 'Kreyòl', '🇭🇹'),
  Lang('ha', 'هوسا', 'Hausa', '🇳🇬'),
  Lang('haw', 'هاوایی', 'ʻŌlelo Hawaiʻi', '🇺🇸'),
  Lang('he', 'عبری', 'עברית', '🇮🇱'),
  Lang('hi', 'هندی', 'हिन्दी', '🇮🇳'),
  Lang('hmn', 'همونگ', 'Hmong', '🌍'),
  Lang('hu', 'مجاری', 'Magyar', '🇭🇺'),
  Lang('is', 'ایسلندی', 'Íslenska', '🇮🇸'),
  Lang('ig', 'ایگبو', 'Igbo', '🇳🇬'),
  Lang('ilo', 'ایلوکانو', 'Ilokano', '🇵🇭'),
  Lang('id', 'اندونزیایی', 'Bahasa Indonesia', '🇮🇩'),
  Lang('ga', 'ایرلندی', 'Gaeilge', '🇮🇪'),
  Lang('it', 'ایتالیایی', 'Italiano', '🇮🇹'),
  Lang('ja', 'ژاپنی', '日本語', '🇯🇵'),
  Lang('jv', 'جاوه‌ای', 'Basa Jawa', '🇮🇩'),
  Lang('kn', 'کانارا', 'ಕನ್ನಡ', '🇮🇳'),
  Lang('kk', 'قزاقی', 'Қазақ', '🇰🇿'),
  Lang('km', 'خمری', 'ខ្មែរ', '🇰🇭'),
  Lang('rw', 'کینیارواندا', 'Ikinyarwanda', '🇷🇼'),
  Lang('gom', 'کونکانی', 'कोंकणी', '🇮🇳'),
  Lang('ko', 'کره‌ای', '한국어', '🇰🇷'),
  Lang('kri', 'کریو', 'Krio', '🇸🇱'),
  Lang('ku', 'کردی', 'Kurdî', '🌍'),
  Lang('ckb', 'کردی سورانی', 'کوردی', '🌍'),
  Lang('ky', 'قرقیزی', 'Кыргызча', '🇰🇬'),
  Lang('lo', 'لائوسی', 'ລາວ', '🇱🇦'),
  Lang('la', 'لاتین', 'Latina', '🏛'),
  Lang('lv', 'لتونی', 'Latviešu', '🇱🇻'),
  Lang('ln', 'لینگالا', 'Lingála', '🇨🇩'),
  Lang('lt', 'لیتوانی', 'Lietuvių', '🇱🇹'),
  Lang('lg', 'لوگاندایی', 'Luganda', '🇺🇬'),
  Lang('lb', 'لوکزامبورگی', 'Lëtzebuergesch', '🇱🇺'),
  Lang('mk', 'مقدونی', 'Македонски', '🇲🇰'),
  Lang('mai', 'مایدیلی', 'मैथिली', '🇮🇳'),
  Lang('ms', 'مالایی', 'Bahasa Melayu', '🇲🇾'),
  Lang('ml', 'مالایالم', 'മലയാളം', '🇮🇳'),
  Lang('mt', 'مالتی', 'Malti', '🇲🇹'),
  Lang('mi', 'ماوری', 'Te Reo Māori', '🇳🇿'),
  Lang('mr', 'مراتی', 'मराठी', '🇮🇳'),
  Lang('mni-Mtei', 'متی میته', 'ꯃꯤꯇꯩꯂꯣꯟ', '🇮🇳'),
  Lang('lus', 'میزو', 'Mizo ṭawng', '🇮🇳'),
  Lang('mn', 'مغولی', 'Монгол', '🇲🇳'),
  Lang('my', 'برمه‌ای', 'မြန်မာ', '🇲🇲'),
  Lang('ne', 'نپالی', 'नेपाली', '🇳🇵'),
  Lang('no', 'نروژی', 'Norsk', '🇳🇴'),
  Lang('ny', 'نیانجا', 'Chichewa', '🇲🇼'),
  Lang('or', 'اودیا', 'ଓଡ଼ିଆ', '🇮🇳'),
  Lang('om', 'اورومو', 'Afaan Oromoo', '🇪🇹'),
  Lang('ps', 'پشتو', 'پښتو', '🇦🇫'),
  Lang('fa', 'فارسی', 'فارسی', '🇮🇷'),
  Lang('pl', 'لهستانی', 'Polski', '🇵🇱'),
  Lang('pt', 'پرتغالی', 'Português', '🇵🇹'),
  Lang('pa', 'پنجابی', 'ਪੰਜਾਬੀ', '🇮🇳'),
  Lang('qu', 'کچوایی', 'Runasimi', '🇵🇪'),
  Lang('ro', 'رومانیایی', 'Română', '🇷🇴'),
  Lang('ru', 'روسی', 'Русский', '🇷🇺'),
  Lang('sm', 'ساموآیی', 'Gagana Samoa', '🇼🇸'),
  Lang('sa', 'سنسکریت', 'संस्कृतम्', '🇮🇳'),
  Lang('gd', 'گیلک اسکاتلندی', 'Gàidhlig', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  Lang('nso', 'سوتوی شمالی', 'Sepedi', '🇿🇦'),
  Lang('sr', 'صربی', 'Српски', '🇷🇸'),
  Lang('st', 'سسوتو', 'Sesotho', '🇱🇸'),
  Lang('sn', 'شونا', 'ChiShona', '🇿🇼'),
  Lang('sd', 'سندی', 'سنڌي', '🇵🇰'),
  Lang('si', 'سینهالی', 'සිංහල', '🇱🇰'),
  Lang('sk', 'اسلواکی', 'Slovenčina', '🇸🇰'),
  Lang('sl', 'اسلووینیایی', 'Slovenščina', '🇸🇮'),
  Lang('so', 'سومالیایی', 'Soomaali', '🇸🇴'),
  Lang('es', 'اسپانیایی', 'Español', '🇪🇸'),
  Lang('su', 'سوندایی', 'Basa Sunda', '🇮🇩'),
  Lang('sw', 'سواحیلی', 'Kiswahili', '🇰🇪'),
  Lang('sv', 'سوئدی', 'Svenska', '🇸🇪'),
  Lang('tg', 'تاجیک', 'Тоҷикӣ', '🇹🇯'),
  Lang('ta', 'تامیل', 'தமிழ்', '🇮🇳'),
  Lang('tt', 'تاتاری', 'Татар', '🇷🇺'),
  Lang('te', 'تلوگو', 'తెలుగు', '🇮🇳'),
  Lang('th', 'تایلندی', 'ไทย', '🇹🇭'),
  Lang('ti', 'تیگرینیا', 'ትግርኛ', '🇪🇷'),
  Lang('ts', 'تسونگا', 'Xitsonga', '🇿🇦'),
  Lang('tr', 'ترکی استانبولی', 'Türkçe', '🇹🇷'),
  Lang('tk', 'ترکمنی', 'Türkmen', '🇹🇲'),
  Lang('ak', 'آکان', 'Akan', '🇬🇭'),
  Lang('uk', 'اوکراینی', 'Українська', '🇺🇦'),
  Lang('ur', 'اردو', 'اردو', '🇵🇰'),
  Lang('ug', 'اویغوری', 'ئۇيغۇرچە', '🇨🇳'),
  Lang('uz', 'ازبکی', 'O‘zbek', '🇺🇿'),
  Lang('vi', 'ویتنامی', 'Tiếng Việt', '🇻🇳'),
  Lang('cy', 'ولزی', 'Cymraeg', '🏴󠁧󠁢󠁷󠁬󠁳󠁿'),
  Lang('xh', 'خوسا', 'isiXhosa', '🇿🇦'),
  Lang('yi', 'یدیش', 'ייִדיש', '🌍'),
  Lang('yo', 'یوروبا', 'Yorùbá', '🇳🇬'),
  Lang('zu', 'زولو', 'isiZulu', '🇿🇦'),
];

Lang langByCode(String code) =>
    kLanguages.firstWhere((l) => l.code == code, orElse: () => Lang(code, code, code, '🌍'));
